---
title: "testing"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(igraph)
library(tools)
library(janitor)
library(htmlwidgets)
```


```{r}
rawEmpirical = read.csv("2seedTransivityData1.csv") %>% 
  dplyr::select(-1) 
rawEmpiricalOld = read.csv("2seedTransivityData.csv") %>% 
  dplyr::select(-1) 
rawEmpirical = rawEmpirical %>% 
  bind_cols(rawEmpiricalOld[, !colnames(rawEmpiricalOld) %in% colnames(rawEmpirical),
                       drop = FALSE]) 

rawRandom = read.csv("2seedTransivityDataRandom1.csv") %>% 
  dplyr::select(-c(1:2)) %>% 
  set_names(paste0("random_", colnames(.))) 
rawRandomOld = read.csv("2seedTransivityDataRandom.csv") %>% 
  dplyr::select(-c(1:2)) %>% 
  set_names(paste0("random_", colnames(.))) 
rawRandom = rawRandom %>% 
  bind_cols(rawRandomOld[, !colnames(rawRandomOld) %in% colnames(rawRandom),
                       drop = FALSE]) %>% 
  set_names(str_replace(colnames(.), "random_", "random_BA_"))




```


```{r}
rawRandom = read.csv("2seedTransivityDataRandom2.csv") %>% 
  dplyr::select(-c(1)) %>%
  dplyr::select(!contains("seeding.method")) %>% 
  select(!contains(colnames(rawRandom))) %>% 
  bind_cols(rawRandom)



rawRandom
```

```{r}
raw = bind_cols(rawEmpirical, rawRandom) 
```


```{r}
clusteringData = read_csv("clusteringData.csv") %>% 
  dplyr::select(-...1) %>% 
  column_to_rownames("network") %>% 
  t() %>% 
  data.frame() %>% 
  t() %>% 
  data.frame() %>% 
  rownames_to_column("network")


clusteringData = clusteringData %>% 
  gather(-network, key = "metric", value = "clustering") %>% 
  mutate(network = ifelse(str_detect(metric, "empirical"), paste0(network, "_"), paste0("random_", network, "_"))) 

```



```{r}
dat = raw %>% 
  set_names(paste0("networks_", colnames(.))) %>% 
  rename(seeding.method = "networks_seeding.method") %>% 
  pivot_longer(starts_with("networks_"), 
               names_to = 'network', 
               values_to = '2tran') %>% 
  mutate(network = str_replace(network, "networks_", "")) %>% 
  mutate(num_nodes = as.numeric(word(network, 2, -1, "num_nodes."))) %>% 
  mutate(network = word(network, 1, 1, "num_nodes.")) %>% 
  mutate(type = ifelse(str_detect(network,"random_"), "Random", "Empirical")) %>%
  mutate(graph = case_when(str_detect(network, "BA") ~ "Barab치si Albert",
                            str_detect(network, "poisson") ~ "Poisson",
                            TRUE ~ "Empirical")) %>%
  mutate(graph = factor(graph, levels = c("Poisson", "Barab치si Albert", "Empirical"))) %>% 
#   filter(!network %in% c("inf.euroroad_", "primary.school.proximity_", "contacts.prox.high.school.2013.attr_", "contacts.prox.high.school.2013_", "webkb.wisc_", "soc.firm.hi.tech_")) %>% 
#   filter(!network %in% paste0("random_", c("inf.euroroad_", "primary.school.proximity_", "contacts.prox.high.school.2013.attr_", "contacts.prox.high.school.2013_", "webkb.wisc_", "random_soc.firm.hi.tech_"))) %>% 
  filter(!network %in% c("inf.euroroad_", "soc.firm.hi.tech_")) %>% 
  filter(!network %in% paste0("random_BA_", c("inf.euroroad_", "soc.firm.hi.tech_"))) %>% 
  filter(!network %in% paste0("random_poisson_", c("inf.euroroad_", "soc.firm.hi.tech_")))

```


```{r}
g = dat %>% 
  filter(num_nodes < 3500) %>% 
  group_by(network, seeding.method, num_nodes, type, graph) %>% 
  summarise(`2tran` = mean(`2tran`)) %>% 
  ungroup() %>% 
  ggplot(aes(num_nodes, `2tran`*3, color = seeding.method, group = seeding.method, 
             label = network)) + 
  geom_point() + 
  geom_line() +
  ggtitle("Two Seed Transitivity over a Range of Network Sizes") +
  theme_classic() +
  ggthemes::scale_colour_tableau() +
  xlab("Number of Network Nodes") +
  ylab("Two Seed Transitivity") +
  facet_wrap(~graph) +
  labs(colour = "Seed Method")

ggplotly(g) %>% 
  saveWidget(file = "plotlyFigures/twoSeedTransMainFigure.html")


# ggsave("twoSeedTransMainFigure.pdf", width = 12, height = 6)
```












# Scatter


```{r}
dataCleaned = dat %>% 
  filter(num_nodes < 3500) %>% 
  group_by(network, seeding.method, num_nodes, type) %>% 
  summarise(`2tran` = mean(`2tran`, na.rm = TRUE)) %>% 
  ungroup() %>% 
  filter(seeding.method != "random") %>% 
  group_by(network) %>% 
  group_modify(~ .x %>% 
                 arrange(seeding.method) %>% 
                 mutate(difference = (`2tran` - lag(`2tran`))/lag(`2tran`) )) %>% 
  ungroup() %>% 
  # filter(!is.na(difference)) %>% 
  mutate(network = str_replace_all(network, "random_", ""))
# %>% 
  # dplyr::select(-seeding.method)


```

```{r}
clusterCleaned = clusteringData %>% 
  mutate(type = ifelse(str_detect(network, "random"), "Random", "Empirical")) %>% 
  # mutate(metric = case_when(str_detect(metric, "SD") & str_detect(metric, "clust") ~ "Clustering SD", 
  #                           str_detect(metric, "SD") & str_detect(metric, "Degree") ~ "Degree SD",
  #                           str_detect(metric, "SD") & str_detect(metric, "Degree") ~ "Degree SD",
  #                           "Clustering SD", "Clustering")) %>% 
  mutate(network = str_replace(network, "random_", ""))
```

```{r}
nodeProperties = read_csv("individualNodeProporties.csv") %>% 
  dplyr::select(-...1) %>% 
  mutate(network = paste0("XYZ", index, "XYZ", network, "_")) %>% 
  column_to_rownames("network") %>% 
  t() %>% 
  data.frame() %>% 
  t() %>% 
  data.frame() %>% 
  rownames_to_column("network") %>% 
  mutate(network = str_replace_all(network, "XYZ", "")) %>% 
  mutate(network = str_replace(network, index, "")) %>% 
  mutate(Triangle = parse_number(Triangle), Degree = parse_number(Degree))



```



```{r}
dataCleaned = dat %>% 
  filter(num_nodes < 3500) %>% 
  group_by(network, seeding.method, num_nodes, type) %>% 
  summarise(`2tran` = mean(`2tran`, na.rm = TRUE)) %>% 
  ungroup() %>% 
  filter(seeding.method != "random") %>% 
  group_by(network) %>% 
  group_modify(~ .x %>% 
                 arrange(`2tran`) %>% 
                 mutate(difference = (`2tran` - lag(`2tran`))/lag(`2tran`) )) %>% 
  ungroup() %>% 
  # filter(!is.na(difference)) %>% 
  mutate(network = str_replace_all(network, "random_", "")) %>% 
  mutate(difference = ifelse(seeding.method == "pair", difference, difference*-1))
```


<!-- ```{r} -->
<!-- g = dataCleaned %>%  -->
<!--   inner_join(nodeProperties) %>%  -->
<!--   filter(!is.na(difference)) %>%  -->
<!--   filter(type == "Empirical") %>%  -->
<!--   filter(network %in% c("aves.weaver.social_",  -->
<!--                         "infect.dublin_", -->
<!--                         "physician_trust_", -->
<!--                         "KKI_", -->
<!--                         "contacts.prox.high.school.2013_", -->
<!--                         "fb.messages_", -->
<!--                         "email_company_", -->
<!--                         "infect.hyper_", -->
<!--                         "uni_email_" -->
<!--                         # "bt.csv_" -->
<!--                         )) %>%  -->
<!--   ggplot(aes(x = Degree, y = Triangle, colour = difference > 0)) + -->
<!--   geom_point() +  -->
<!--   theme_classic() + -->
<!--   facet_wrap(~network) + -->
<!--   ggthemes::scale_colour_tableau() -->

<!-- ggplotly(g) -->
<!-- ``` -->

```{r}
g = dataCleaned %>%
  inner_join(nodeProperties) %>%
  filter(!is.na(difference)) %>%
  filter(type == "Empirical") %>%
  group_by(network) %>%
  mutate(totalTriangles = sum(Triangle)) %>%
  mutate(Degree = max(Degree)) %>%
  dplyr::slice(1) %>%
  filter(num_nodes > 100) %>%
  # filter(network %in% c("aves.weaver.social_",
  #                       "infect.dublin_",
  #                       "physician_trust_",
  #                       "KKI_",
  #                       "fb.messages_",
  #                       "email_company_",
  #                       "infect.hyper_")) %>%
  mutate(Seeding = ifelse(difference > 0, "Pair is Better", "Friend is Better")) %>%
  ggplot(aes(x =  Degree, y = difference, colour = Seeding, label = paste0(network, num_nodes))) +
  geom_point() +
  theme_classic() +
  ggthemes::scale_colour_tableau()  +
  xlab("Max Degree of Network") +
  ylab("Weighted % Difference in Two Seed Transitivity") +
  ggtitle("Maximum Degree of a Network vs % Difference in Two Seed Transitivity in Empirical Networks") +
  labs(colour = "Better Method")


ggplotly(g) %>% 
  saveWidget(file = "plotlyFigures/maxDegreeVSdifference.html")


ggsave("maxDegreeVSdifference.pdf", width = 12, height = 6)


```



```{r}
g = nodeProperties %>% 
  group_by(network) %>% 
  mutate(TotalTriangles = sum(Triangle)) %>% 
  mutate(Ratio = Triangle/TotalTriangles) %>% 
  filter(str_detect(network, "fb.messages_")) %>% 
  mutate(network = str_replace_all(network, "\\.|_", " ") %>% str_to_title()) %>%
  mutate(network = str_replace_all(network, "Random|_", "Barab치si Albert") %>% str_to_title()) %>%
  ggplot(aes(x = Degree, y = Ratio)) +
  geom_point() +
  # geom_smooth(method = "lm") +
  theme_classic() + 
  facet_wrap(~network) +
  ylab("Proportion of Triangles at Node") +
  ggtitle("Random BA Graph Model vs Empirical (Friend Seeding had highest Two-Seed Transitivity in Empirical)")

ggplotly(g) %>% 
  saveWidget(file = "plotlyFigures/randomVsempiricalFriend.html")


# ggsave("randomVsempiricalFriend.pdf", width = 12, height = 6)

```

```{r}
nodeProperties %>% 
  group_by(network) %>% 
  mutate(TotalTriangles = sum(Triangle)) %>% 
  mutate(Ratio = Triangle/TotalTriangles) %>% 
  filter(str_detect(network, "aves.weaver.social_")) %>% 
  mutate(network = str_replace_all(network, "\\.|_", " ") %>% str_to_title()) %>%
  mutate(network = str_replace_all(network, "Random|_", " Barab치si Albert") %>% str_to_title()) %>%
  ggplot(aes(x = Degree, y = Ratio)) +
  geom_point() +
  # geom_smooth(method = "lm") +
  theme_classic() + 
  facet_wrap(~network) +
  ylab("Proportion of Triangles at Node") +
  ggtitle("Random BA Graph Model vs Empirical (Pair Seeding had highest Two-Seed Transitivity in Empirical)")
ggsave("randomVsempiricalPair.pdf", width = 12, height = 6)
```


```{r}
g = nodeProperties %>% 
  group_by(network) %>% 
  mutate(TotalTriangles = sum(Triangle)) %>% 
  mutate(Ratio = Triangle/TotalTriangles) %>% 
  filter(!str_detect(network, "random")) %>% 
  filter(str_detect(network, "KKI_|fb.messages_|aves.weaver.social_|email_company_|physician_trust_|soc.hamsterster_")) %>%
  mutate(Seeding = case_when(network == "KKI_" ~ "Pair",
                             network == "aves.weaver.social_" ~ "Pair",
                             network == "physician_trust_" ~ "Pair",
                             network == "soc.hamsterster_" ~ "Friend",
                             network == "email_company_" ~ "Friend",
                             network == "fb.messages_" ~ "Friend",
                             )) %>% 
  mutate(network = str_replace_all(network, "\\.|_", " ") %>% str_to_title()) %>%
  mutate(network = ifelse(network == "Kki ", "KKI", network)) %>% 
  arrange(Seeding) %>% 
  mutate(network = factor(network, levels = unique(.$network), ordered = TRUE)) %>% 
  ggplot(aes(x = Degree, y = Ratio, colour = Seeding))   +
  geom_point() +
  theme_classic() +
  facet_wrap(~ network) +
  ylab("Proportion of Triangles at Node") +
  ggthemes::scale_colour_tableau() +
  labs(colour = "Better Method") + 
  ggtitle("Comparison of Degree vs Triangles across Pair and Friend Dominating Seeding")



ggplotly(g) %>% 
  saveWidget(file = "plotlyFigures/degreeVStriangles.html")

ggsave("degreeVStriangles.pdf", width = 12, height = 6)
```

