---
title: "testing"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(igraph)
library(tools)
library(janitor)
library(htmlwidgets)
library(ggthemes)
```


```{r}
figure5 = read_csv("figure_5.csv") %>% 
  mutate(version = ifelse(version == "BA","Barabási Albert", "Empirical")) %>% 
  mutate(network = str_replace_all(network, "_"," ") %>% str_to_title())
```



```{r}
g = figure5 %>% 
  mutate(version = factor(version, levels = c("Empirical", "Barabási Albert"))) %>% 
  ggplot(aes(x = N, y = critical_q, colour = seeding_method, label = network)) +
  geom_point() +
  geom_line() +
  theme_classic() +
  scale_colour_tableau() +
  facet_wrap(~version) +
  labs(colour = "Seed Method", y = "Critical q") +
  ggtitle("")


ggplotly(g) %>% 
  layout(width = 800) %>% 
  saveWidget(file = "nVScascade.html")


g %>% 
  saveRDS(file = "nVScascade.RDS")
```


```{r}
(figure5 %>% 
  ggplot(aes(x = N, y = critical_q, colour = seeding_method, label = network)) +
  geom_smooth(se = FALSE) +
  theme_classic() +
  scale_colour_tableau() +
  facet_wrap(~version) +
  labs(colour = "Seed Method", y = "Critical q") +
  ggtitle("Cascade Threshold Comparison Across Seeding Methods")) %>% 
  ggplotly()
```


```{r}
figure11 = read_csv("figure_11.csv")
```


```{r}
g = figure11 %>%
  mutate(network = str_replace_all(network, "_"," ") %>% str_to_title()) %>% 
  ggplot(aes(x = q, y = proportion_adopted, colour = seeding_method)) +
  geom_point() +
  geom_line() +
  scale_colour_tableau() +
  theme_classic() +
  labs(colour = "Seed Method", y = "Proportion of Nodes Adopting Innovation") +
  ggtitle("") +
  facet_wrap(~network)

ggplotly(g)


g %>%
  saveRDS(file = "qVSprop.RDS")
```



```{r}
spreading = read_csv("spreading_proportions.csv") %>% 
  select(contains("fb_friends.csv N=800"), times, seeding) %>% 
  set_names(c("fb_friends", "Times", "Seeding"))



g = spreading %>%
  # mutate(network = str_replace_all(network, "_"," ") %>% str_to_title()) %>% 
  ggplot(aes(x = Times, y = fb_friends, colour = Seeding)) +
  geom_point() +
  geom_line() +
  scale_colour_tableau() +
  theme_classic() +
  labs(colour = "Seed Method", 
       y = "Proportion of Nodes Adopting Innovation",
       x = "Iteration Step (Time)") +
  ggtitle("")

ggplotly(g)


g %>%
  saveRDS(file = "spreading.RDS")
```


